/*
 * Copyright (c) 2020-present Lawly AB. All Rights Reserved.
 * Author: Mehdi Tirgar <mehdi.tirgar@wearelevels.com> 2020-2021
 *
 */

import { ReactComponent as ArrowDown } from './assets/arrow-down.svg';
import { ReactComponent as ArrowRight } from './assets/arrow-right.svg';
import { ReactComponent as Book } from './assets/book.svg';
import { ReactComponent as BullseyePointer } from './assets/bullseye-pointer.svg';
import { ReactComponent as CaretLeft } from './assets/caret-left.svg';
import { ReactComponent as Check } from './assets/check.svg';
import { ReactComponent as ClipboardListCheck } from './assets/clipboard-list-check.svg';
import { ReactComponent as Clipboard } from './assets/clipboard.svg';
import { ReactComponent as CommentAltEdit } from './assets/comment-alt-edit.svg';
import { ReactComponent as CommentAltExcl } from './assets/comment-alt-exclamation.svg';
import { ReactComponent as Cubes } from './assets/cubes.svg';
import { ReactComponent as DoorOpen } from './assets/door-open.svg';
import { ReactComponent as EllipsisV } from './assets/ellipsis-v.svg';
import { ReactComponent as ExclamationCircle } from './assets/exclamation-circle.svg';
import { ReactComponent as ExclamationSquare } from './assets/exclamation-square.svg';
import { ReactComponent as ExclamationTriangle } from './assets/exclamation-triangle.svg';
import { ReactComponent as FileContact } from './assets/file-contract.svg';
import { ReactComponent as FolderTree } from './assets/folder-tree.svg';
import { ReactComponent as GraduationCap } from './assets/graduation-cap.svg';
import { ReactComponent as InfoCircle } from './assets/info-circle.svg';
import { ReactComponent as Keyboard } from './assets/keyboard.svg';
import { ReactComponent as LayerPlus } from './assets/layer-plus.svg';
import { ReactComponent as LongArrowLeft } from './assets/long-arrow-left.svg';
import { ReactComponent as ParagraphRtl } from './assets/paragraph-rtl.svg';
import { ReactComponent as PlayCircle } from './assets/play-circle.svg';
import { ReactComponent as Plus } from './assets/plus.svg';
import { ReactComponent as PollPeople } from './assets/poll-people.svg';
import { ReactComponent as PortalExit } from './assets/portal-exit.svg';
import { ReactComponent as Presentation } from './assets/presentation.svg';
import { ReactComponent as GDPR } from './assets/gdpr-icon.svg';
import { ReactComponent as ProjectDiagram } from './assets/project-diagram.svg';
import { ReactComponent as Scrubber } from './assets/scrubber.svg';
import { ReactComponent as Server } from './assets/server.svg';
import { ReactComponent as SortSizeUp } from './assets/sort-size-up.svg';
import { ReactComponent as SpellCheck } from './assets/spell-check.svg';
import { ReactComponent as StoreSlash } from './assets/store-slash.svg';
import { ReactComponent as Times } from './assets/times.svg';
import { ReactComponent as Toolbox } from './assets/toolbox.svg';
import { ReactComponent as Typewriter } from './assets/typewriter.svg';
import { ReactComponent as UserCheck } from './assets/user-check.svg';
import { ReactComponent as UserRobot } from './assets/user-robot.svg';
import { ReactComponent as WindowClose } from './assets/window-close.svg';
import { createSvgIcon } from './utils';

export const ArrowDownIcon = createSvgIcon(ArrowDown);
export const ArrowRightIcon = createSvgIcon(ArrowRight);
export const BookIcon = createSvgIcon(Book);
export const BullseyePointerIcon = createSvgIcon(BullseyePointer);
export const CaretLeftIcon = createSvgIcon(CaretLeft);
export const CheckIcon = createSvgIcon(Check);
export const ClipboardIcon = createSvgIcon(Clipboard);
export const ClipboardListCheckIcon = createSvgIcon(ClipboardListCheck);
export const CommentAltExclIcon = createSvgIcon(CommentAltExcl);
export const CommentAltEditIcon = createSvgIcon(CommentAltEdit);
export const CubesIcon = createSvgIcon(Cubes);
export const DoorOpenIcon = createSvgIcon(DoorOpen);
export const EllipsisVIcon = createSvgIcon(EllipsisV);
export const ExclamationCircleIcon = createSvgIcon(ExclamationCircle);
export const ExclamationSquareIcon = createSvgIcon(ExclamationSquare);
export const ExclamationTriangleIcon = createSvgIcon(ExclamationTriangle);
export const FileContactIcon = createSvgIcon(FileContact);
export const FolderTreeIcon = createSvgIcon(FolderTree);
export const GraduationCapIcon = createSvgIcon(GraduationCap);
export const InfoCircleIcon = createSvgIcon(InfoCircle);
export const KeyboardIcon = createSvgIcon(Keyboard);
export const LayerPlusIcon = createSvgIcon(LayerPlus);
export const LongArrowLeftIcon = createSvgIcon(LongArrowLeft);
export const ParagraphRtlIcon = createSvgIcon(ParagraphRtl);
export const PollPeopleIcon = createSvgIcon(PollPeople);
export const PlayCircleIcon = createSvgIcon(PlayCircle);
export const PlusIcon = createSvgIcon(Plus);
export const PortalExitIcon = createSvgIcon(PortalExit);
export const PresentationIcon = createSvgIcon(Presentation);
export const GDPRIcon = createSvgIcon(GDPR);
export const ProjectDiagramIcon = createSvgIcon(ProjectDiagram);
export const ScrubberIcon = createSvgIcon(Scrubber);
export const ServerIcon = createSvgIcon(Server);
export const SortSizeUpIcon = createSvgIcon(SortSizeUp);
export const SpellCheckIcon = createSvgIcon(SpellCheck);
export const StoreSlashIcon = createSvgIcon(StoreSlash);
export const TimesIcon = createSvgIcon(Times);
export const ToolboxIcon = createSvgIcon(Toolbox);
export const TypewriterIcon = createSvgIcon(Typewriter);
export const UserCheckIcon = createSvgIcon(UserCheck);
export const UserRobotIcon = createSvgIcon(UserRobot);
export const WindowCloseIcon = createSvgIcon(WindowClose);
